### ISSUE TITLE
Blender 4.0 support??

### ISSUE THREAD

**Issue by JohnJefferson98** [DrachenSeele/SuperImageDenoiser#19]
I'm testing SID and SAC in Blender 4.0 and I'm getting errors. Is there a way to fix it or someone can optimize it for version 4.0??

 Thank you, this addon is a complete time saver and super functional

**Comment by DrachenSeele** [comment]
Hi,
This has been resolved with the BETA version of SID and SAC. There won't be further development on this repository, as all development moved to our combined addon.
You can get it here on blendermarket.
https://blendermarket.com/products/pidgeontoolbag

**Comment by DrachenSeele** [comment]
Closing issue because it has been resolved.
